// Regenerates src/abis.ts and src/bytecode.ts from Foundry build output (run `forge build` first).
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const out = resolve(import.meta.dirname, '../../../contracts/out')
const names = ['KeycardRegistry', 'LineBook', 'CreditTerms', 'CollateralVault'] as const
let abis = '// GENERATED by scripts/export-abis.ts — do not edit\n'
let code = '// GENERATED by scripts/export-abis.ts — do not edit\n'
for (const n of names) {
  const j = JSON.parse(readFileSync(`${out}/${n}.sol/${n}.json`, 'utf8'))
  abis += `export const ${n[0].toLowerCase() + n.slice(1)}Abi = ${JSON.stringify(j.abi, null, 2)} as const\n`
  code += `export const ${n[0].toLowerCase() + n.slice(1)}Bytecode = '${j.bytecode.object}' as const\n`
}
writeFileSync(resolve(import.meta.dirname, '../src/abis.ts'), abis)
writeFileSync(resolve(import.meta.dirname, '../src/bytecode.ts'), code)
console.log('wrote src/abis.ts, src/bytecode.ts')
